"""
Pipeline Display
=================
DO NOT EDIT THIS FILE -- pre-built Rich display helpers for the pipeline.

Uses the ``rich`` library to render live pipeline statistics,
active-run tables, and a final summary panel.
"""

from __future__ import annotations

from rich.console import Console
from rich.live import Live
from rich.panel import Panel
from rich.table import Table

from sdk_do_not_edit import ActiveRun

console = Console()


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def display_active_runs(runs: list[ActiveRun]) -> None:
    """Print a table of active experiment runs."""
    if not runs:
        console.print("[yellow]No active runs found.[/yellow]")
        return

    table = Table(title="Active Experiment Runs", show_lines=True)
    table.add_column("Run ID", style="cyan", no_wrap=True)
    table.add_column("Name", style="green")
    table.add_column("Model", style="magenta")
    table.add_column("Status", style="bold")

    for run in runs:
        table.add_row(run.id, run.name, run.model_type, run.status)

    console.print(table)


def display_pipeline_stats(snapshot: dict) -> None:
    """Print a one-shot view of current pipeline statistics."""
    if not snapshot:
        return

    table = _build_stats_table(snapshot)
    console.print(table)


def display_final_summary(snapshot: dict, elapsed: float) -> None:
    """Print a final summary panel after the pipeline completes."""
    if not snapshot:
        console.print("[yellow]No snapshot data to display.[/yellow]")
        return

    total = snapshot.get("total_ingested", 0)
    valid = snapshot.get("total_validated", 0)
    invalid = snapshot.get("total_invalid", 0)
    errors = snapshot.get("total_errors", 0)
    throughput = total / elapsed if elapsed > 0 else 0

    lines = [
        f"[bold]Total metrics ingested:[/bold]  {total}",
        f"[bold]Valid:[/bold]                    {valid}",
        f"[bold]Invalid:[/bold]                  {invalid}",
        f"[bold]Errors:[/bold]                   {errors}",
        f"[bold]Elapsed:[/bold]                  {elapsed:.2f}s",
        f"[bold]Throughput:[/bold]               {throughput:.1f} metrics/sec",
    ]

    metrics = snapshot.get("metrics", {})
    if metrics:
        lines.append("")
        lines.append("[bold underline]Per-Metric Summary[/bold underline]")
        for name, stats in sorted(metrics.items()):
            count = stats.get("count", 0)
            avg = stats.get("avg", 0.0)
            mn = stats.get("min", 0.0)
            mx = stats.get("max", 0.0)
            lines.append(
                f"  {name:<20s}  count={count:<4d}  avg={avg:.4f}  "
                f"min={mn:.4f}  max={mx:.4f}"
            )

    per_run = snapshot.get("per_run", {})
    if per_run:
        lines.append("")
        lines.append("[bold underline]Per-Run Summary[/bold underline]")
        for run_id, info in sorted(per_run.items()):
            count = info.get("count", 0)
            last_step = info.get("last_step", 0)
            lines.append(f"  {run_id:<12s}  metrics={count:<4d}  last_step={last_step}")

    panel = Panel(
        "\n".join(lines),
        title="[bold green]Pipeline Complete[/bold green]",
        border_style="green",
        expand=False,
    )
    console.print(panel)


def create_live_display() -> Live:
    """Return a ``rich.live.Live`` context manager for live-updating stats."""
    return Live(console=console, refresh_per_second=4)


def format_stats_table(snapshot: dict) -> Table:
    """
    Build a Rich ``Table`` from a pipeline snapshot dict.

    Suitable for use inside a ``Live`` context::

        with create_live_display() as live:
            live.update(format_stats_table(snapshot))
    """
    if not snapshot:
        table = Table(title="Pipeline Stats (waiting for data...)")
        return table

    return _build_stats_table(snapshot)


# ---------------------------------------------------------------------------
# Internal
# ---------------------------------------------------------------------------


def _build_stats_table(snapshot: dict) -> Table:
    total = snapshot.get("total_ingested", 0)
    valid = snapshot.get("total_validated", 0)
    invalid = snapshot.get("total_invalid", 0)
    errors = snapshot.get("total_errors", 0)

    table = Table(title="Pipeline Statistics", show_lines=True, expand=False)
    table.add_column("Stat", style="bold cyan", no_wrap=True)
    table.add_column("Value", justify="right")

    table.add_row("Total Ingested", str(total))
    table.add_row("Validated", f"[green]{valid}[/green]")
    table.add_row("Invalid", f"[red]{invalid}[/red]" if invalid else "0")
    table.add_row("Errors", f"[red]{errors}[/red]" if errors else "0")

    metrics = snapshot.get("metrics", {})
    if metrics:
        table.add_section()
        table.add_row("[bold]Metric Name[/bold]", "[bold]count / avg / min / max[/bold]")
        for name, stats in sorted(metrics.items()):
            count = stats.get("count", 0)
            avg = stats.get("avg", 0.0)
            mn = stats.get("min", 0.0)
            mx = stats.get("max", 0.0)
            table.add_row(
                name,
                f"{count}  /  {avg:.4f}  /  {mn:.4f}  /  {mx:.4f}",
            )

    per_run = snapshot.get("per_run", {})
    if per_run:
        table.add_section()
        table.add_row("[bold]Run ID[/bold]", "[bold]metrics / last_step[/bold]")
        for run_id, info in sorted(per_run.items()):
            count = info.get("count", 0)
            last_step = info.get("last_step", 0)
            table.add_row(run_id, f"{count}  /  step {last_step}")

    return table
