"""
Mocked Weights & Biases Metrics Streaming SDK
===============================================
DO NOT EDIT THIS FILE -- it simulates a third-party SDK.

This SDK provides access to real-time metric streams from active ML experiments.

Classes:
    WandbMetricsSDK - Main SDK client
    ActiveRun - An active experiment run
    Metric - A single metric data point
    RateLimitError - Raised when rate limit is exceeded

Methods:
    list_active_runs(project_id: str) -> list[ActiveRun]
        Returns active runs for a project. ~100ms delay.
        Raises ValueError if project_id is empty.

    stream_run_metrics(run_id: str) -> Generator[Metric, None, None]
        Generator that yields Metric objects every 50-200ms.
        Yields 8-15 metrics per run, then stops.
        Raises ValueError if run_id is empty or not found.

    validate_metric(metric: Metric) -> bool
        Validates a metric's structure. ~50ms delay.
        RATE LIMITED: max 20 calls per second. Raises RateLimitError if exceeded.
        Returns True if valid, False if invalid (~10% chance of invalid).
"""

from __future__ import annotations

import random
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Generator


class RateLimitError(Exception):
    """Raised when the SDK rate limit is exceeded (max 20 validate_metric calls/sec)."""

    def __init__(self, message: str = "Rate limit exceeded: max 20 validate_metric calls per second"):
        super().__init__(message)


@dataclass
class ActiveRun:
    """Represents an active ML experiment run."""
    id: str
    name: str
    model_type: str
    started_at: float
    status: str = "running"


@dataclass
class Metric:
    """A single metric data point from a run."""
    run_id: str
    step: int
    metric_name: str
    value: float
    timestamp: float


# ---------------------------------------------------------------------------
# Internal data
# ---------------------------------------------------------------------------

_METRIC_RANGES: dict[str, tuple[float, float]] = {
    "loss": (0.01, 2.0),
    "accuracy": (0.5, 0.99),
    "learning_rate": (0.0001, 0.01),
    "gpu_utilization": (0.3, 1.0),
    "memory_usage": (0.2, 0.95),
}

_METRIC_NAMES = list(_METRIC_RANGES.keys())

_RUNS: dict[str, list[ActiveRun]] = {
    "gpu-training": [
        ActiveRun(
            id="run-001",
            name="resnet50-baseline",
            model_type="ResNet-50",
            started_at=time.time() - 3600,
        ),
        ActiveRun(
            id="run-002",
            name="vit-large-finetune",
            model_type="ViT-L/16",
            started_at=time.time() - 2400,
        ),
        ActiveRun(
            id="run-003",
            name="bert-ner-sweep",
            model_type="BERT-base",
            started_at=time.time() - 1800,
        ),
        ActiveRun(
            id="run-004",
            name="gpt2-lora-adapt",
            model_type="GPT-2",
            started_at=time.time() - 1200,
        ),
        ActiveRun(
            id="run-005",
            name="efficientnet-b4-aug",
            model_type="EfficientNet-B4",
            started_at=time.time() - 900,
        ),
        ActiveRun(
            id="run-006",
            name="llama-qlora-chat",
            model_type="LLaMA-7B",
            started_at=time.time() - 600,
        ),
    ],
}

_VALID_RUN_IDS = {run.id for runs in _RUNS.values() for run in runs}


class WandbMetricsSDK:
    """Main SDK client for streaming ML experiment metrics."""

    def __init__(self) -> None:
        self._validate_timestamps: deque[float] = deque()
        self._rate_lock = threading.Lock()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def list_active_runs(self, project_id: str) -> list[ActiveRun]:
        """
        Return the active runs for *project_id*.

        Simulates ~100 ms network latency.
        Raises ``ValueError`` if *project_id* is empty.
        """
        if not project_id:
            raise ValueError("project_id must not be empty")
        time.sleep(0.1)
        return list(_RUNS.get(project_id, []))

    def stream_run_metrics(self, run_id: str) -> Generator[Metric, None, None]:
        """
        Generator that yields :class:`Metric` objects for *run_id*.

        Each call yields 8-15 metrics with 50-200 ms between yields,
        then the generator is exhausted.

        Raises ``ValueError`` if *run_id* is empty or unknown.
        """
        if not run_id:
            raise ValueError("run_id must not be empty")
        if run_id not in _VALID_RUN_IDS:
            raise ValueError(f"Unknown run_id: {run_id!r}")

        num_metrics = random.randint(8, 15)
        for step in range(1, num_metrics + 1):
            metric_name = random.choice(_METRIC_NAMES)
            lo, hi = _METRIC_RANGES[metric_name]
            value = round(random.uniform(lo, hi), 6)
            yield Metric(
                run_id=run_id,
                step=step,
                metric_name=metric_name,
                value=value,
                timestamp=time.time(),
            )
            time.sleep(random.uniform(0.05, 0.2))

    def validate_metric(self, metric: Metric) -> bool:
        """
        Validate a metric's structure.

        Simulates ~50 ms processing time.

        **Rate limited** -- at most 20 calls per second.  Raises
        :class:`RateLimitError` if the limit is exceeded.

        Returns ``True`` if the metric is valid, ``False`` otherwise
        (~10 % chance of returning ``False``).
        """
        now = time.time()

        with self._rate_lock:
            # Purge timestamps older than 1 second
            while self._validate_timestamps and self._validate_timestamps[0] < now - 1.0:
                self._validate_timestamps.popleft()
            if len(self._validate_timestamps) >= 20:
                raise RateLimitError()
            self._validate_timestamps.append(now)

        time.sleep(0.05)

        # ~10 % chance of an "invalid" metric
        return random.random() > 0.10
